### ISSUE TITLE
Oracle Switch Schema

### ISSUE THREAD

**Issue by bhugot** [sharpmigrations/sharpmigrations#9]
Hello,

Is there a way to change current_schema for sharpmigrations.

I use Oracle and I have One connection in my connectionStrings but i usualy switch from one schema to another. How can I do that for sharpmigrations Table.

I can copy paste the actual Database implementation to add the switch in OpenConnection but I would prefer to have it implemented in official version.

I think we should be able for migration to specify the schema in AddTable by example.

**Comment by andrecarlucci** [comment]
Sounds like something that we should have on all DDL commands, right?

Is it something globally like: "run all these migrations on this schema" or on a set of migrations, "some commands go for one schema and others to another"?

**Comment by bhugot** [comment]
For migrations you could have another parameter in Add.Table("TableName","SchemaName")
But we need to be able to specify the SchemaName for the SharpMigrations Table too.

**Comment by andrecarlucci** [comment]
Got it. I'll work on that.

André Carlucci
twitter/andrecarlucci
Microsoft MVP
Intel Innovator
www.andrecarlucci.com
